package mapi

type SearchKeywords struct {
	Data struct {
		Ads []struct {
			ID         int    `json:"id"`
			URL        string `json:"url"`  // 项目URL
			Text       string `json:"text"` // 搜索框推广显示
			ShowTag    int    `json:"show_tag"`
			ProjectID  int    `json:"project_id"`  // 项目ID
			ProClass   int    `json:"pro_class"`   // 项目类别
			AdPosition string `json:"ad_position"` // 广告位置，"search_key_words"
			Width      string `json:"width"`
			High       string `json:"high"`
			IsSort     bool   `json:"is_sort"`
			StartTime  string `json:"start_time"` // 推广起始时间?
		} `json:"ads"`
	} `json:"data"`
	MapiQueryTime int    `json:"mapi_query_time"` // API请求时间戳
	Message       string `json:"message"`
	Status        int    `json:"status"`
	SysMsg        string `json:"sys_msg"`
}

type HotList struct {
	Data struct {
		MallHotList struct {
			Category string `json:"category"`
			List     []struct {
				ImgURL    string `json:"img_url"`    // 项目图片链接
				Name      string `json:"name"`       // 项目名称
				ProductID string `json:"product_id"` // 项目ID
			} `json:"list"`
			Tip   string `json:"tip"`   // "排序由销量、搜索、好评等综合得出"
			Title string `json:"title"` //"商品热销榜"
		} `json:"mall_hot_list"`
	} `json:"data"`
	MapiQueryTime int    `json:"mapi_query_time"`
	Message       string `json:"message"`
	Status        int    `json:"status"`
	SysMsg        string `json:"sys_msg"`
}

type ProductListRefresh struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
	Data    []struct {
		ID          int    `json:"id"`           // 项目ID
		BackerMoney string `json:"backer_money"` // 已筹金额,如"21.8万"
		BackerCount string `json:"backer_count"` // 支持者人数,如"123人"
		ProClass    string `json:"pro_class"`    // 项目类别
		Status      string `json:"status"`       // 项目状态,如"众筹中"
		ShortTitle  string `json:"short_title"`  // 项目短标题
		Logo        string `json:"logo"`         // 项目图片地址
		UserInfo    struct {
			ID       int    `json:"id"`       // 发起人ID
			Username string `json:"username"` // 发起人用户名
			Icon     string `json:"icon"`     // 发起人头像
		} `json:"user_info"`
		URL            string `json:"url"`                       // 项目地址
		Progress       string `json:"progress"`                  // 众筹进度,如"344.31"
		CommentCount   int    `json:"comment_count,omitempty"`   // 项目评论数
		BullishCount   int    `json:"bullish_count,omitempty"`   // 看好人数(用于创意)
		SubscribeCount string `json:"subscribe_count,omitempty"` // 看好人数,如"233"
		IfSubscribe    int    `json:"if_subscribe,omitempty"`    // 是否看好
		CountDown      string `json:"count_down,omitempty"`      // 项目开始日期(用于预热项目)
		StartTime      string `json:"start_time,omitempty"`      // 项目开始日期(用于众筹中项目)
	} `json:"data"`
}

type AutoGenerated struct {
	Status  int    `json:"status"`
	Message string `json:"message"`
	Data    struct {
		ProjectList []struct {
			ID                string      `json:"id"`                  // 项目ID
			ProClass          string      `json:"pro_class"`           // 项目类型
			ShortTitle        string      `json:"short_title"`         // 项目短标题
			IfHideBackerInfo  string      `json:"if_hide_backer_info"` // 是否隐藏众筹者信息
			BackerMoney       string      `json:"backer_money"`        // 已筹金额(带货币符号)
			BackerCount       int         `json:"backer_count"`        // 支持者人数
			StartTime         string      `json:"start_time"`          // 众筹开始时间
			SubscribeCount    int         `json:"subscribe_count"`     // 看好人数
			CommentNum        string      `json:"comment_num"`         // 评论数量
			Category          string      `json:"category"`            // 项目中文分类
			EndTime           string      `json:"end_time"`            // 众筹截止时间
			ExamineModifyTime interface{} `json:"examine_modify_time"` // 暂不确定这里会返回什么，目前测试是返回null
			Logo4X3           string      `json:"logo4x3"`             // 项目4x3Logo URL
			Logo7X3           string      `json:"logo7x3"`             // 项目7x3Logo URL
			Percent           int         `json:"percent"`             // 项目进展(不带百分号)
			Recommended       int         `json:"recommended"`         // 作用未知
			StatusCode        int         `json:"status_code"`         // 项目状态码
			StatusZh          string      `json:"status_zh"`           // 项目中文状态
			IfSubscribe       int         `json:"if_subscribe"`        // 是否订阅
			IfFavor           int         `json:"if_favor"`            // 是否喜爱
			BullishCount      int         `json:"bullish_count"`       // 看好人数
			FavorCount        int         `json:"favor_count"`         // 看好人数
			UserInfo          struct {
				ID       string `json:"id"`
				Username string `json:"username"`
				Icon     string `json:"icon"`
			} `json:"user_info"`
		} `json:"project_list"`
	} `json:"data"`
}
